from __future__ import annotations

import argparse
import base64
import io
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_WEB_ROOT = ROOT / "web"
OUTPUT = ROOT / "tools" / "embedded_web_assets.py"


def build_archive(web_root: Path = DEFAULT_WEB_ROOT) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(web_root.rglob("*")):
            if not path.is_file():
                continue
            relative = path.relative_to(web_root).as_posix()
            info = zipfile.ZipInfo(relative, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, path.read_bytes(), compresslevel=9)
    return buffer.getvalue()


def render_module(archive_bytes: bytes) -> str:
    encoded = base64.b85encode(archive_bytes).decode("ascii")
    chunks = [encoded[index:index + 100] for index in range(0, len(encoded), 100)]
    payload = "\n".join(f'    "{chunk}"' for chunk in chunks)
    return f'''# Generated by tools/build_embedded_web_assets.py. Do not edit manually.
from __future__ import annotations

import base64
import io
import zipfile
from pathlib import PurePosixPath
from threading import RLock


_ENCODED_ARCHIVE = (\n{payload}\n)
_ARCHIVE_BUFFER = io.BytesIO(base64.b85decode(_ENCODED_ARCHIVE))
_ARCHIVE = zipfile.ZipFile(_ARCHIVE_BUFFER, "r")
_NAMES = frozenset(_ARCHIVE.namelist())
_LOCK = RLock()


def read_embedded_web_asset(relative: str) -> bytes | None:
    normalized = PurePosixPath(str(relative).replace("\\\\", "/")).as_posix().lstrip("/")
    if not normalized or normalized.startswith("../") or "/../" in normalized or normalized not in _NAMES:
        return None
    with _LOCK:
        return _ARCHIVE.read(normalized)
'''


def main() -> None:
    parser = argparse.ArgumentParser(description="Embed FMODD web assets in a Python module.")
    parser.add_argument("--web-root", type=Path, default=DEFAULT_WEB_ROOT)
    args = parser.parse_args()
    web_root = args.web_root.resolve()
    if not web_root.is_dir():
        raise SystemExit(f"Web asset directory does not exist: {web_root}")

    archive_bytes = build_archive(web_root)
    rendered = render_module(archive_bytes)
    changed = not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered
    if changed:
        OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    file_count = sum(1 for path in web_root.rglob("*") if path.is_file())
    status = "updated" if changed else "unchanged"
    print(
        f"embedded {file_count} files into {OUTPUT} "
        f"({len(archive_bytes)} archive bytes, {status})"
    )


if __name__ == "__main__":
    main()
