(() => {
  "use strict";

  // Loaded before i18n.js.  The core snapshots this registry at startup so
  // shell rendering can use stable semantic keys without owning the core.
  const messages = Object.freeze({
    "en-GB": Object.freeze({
      "shell.intelligence_title.one": "Intelligence Centre found {count} fixture with available intelligence", "shell.intelligence_title.other": "Intelligence Centre found {count} fixtures with available intelligence", "shell.intelligence_aria.one": "Activities: Intelligence Centre has {count} fixture with available intelligence", "shell.intelligence_aria.other": "Activities: Intelligence Centre has {count} fixtures with available intelligence", "home.active_days.one": "{count} active day", "home.active_days.other": "{count} active days", "home.bets.one": "{count} bet", "home.bets.other": "{count} bets", "manager.merge_title.one": "Merge the current same-ID account into a new account", "manager.merge_title.other": "Merge the current {count} same-ID accounts into a new account", "topbar.up_to_date_settled.one": "Up to date · {count} bet settled", "topbar.up_to_date_settled.other": "Up to date · {count} bets settled",
      "common.cancel": "Cancel", "common.close": "Close", "common.confirm": "Confirm", "common.ok": "OK",
      "funding.available": "Available funds", "funding.bank": "Bank {amount}", "funding.wallet": "Wallet {amount}", "funding.recurring": "{label} {amount}",
      "time.tbc": "Time TBC", "shell.game_time": "Game time {date} {time}", "shell.not_connected": "No save connected", "shell.market_duration": "90 min",
      "shell.wallet_balance": "Wallet, balance {amount}", "shell.intelligence_title": "Intelligence Centre found {count} fixture(s) with available intelligence", "shell.intelligence_aria": "Activities, Intelligence Centre has {count} fixture(s) with available intelligence", "shell.activities": "Activities",
      "request.in_progress": "This operation is already in progress. Do not submit it again.", "request.state_timeout": "Save data is still loading in the background. The interface will continue to sync automatically; do not refresh again.", "request.read_timeout": "Reading the local service timed out. The interface has recovered; background loading may still continue, so try again later.", "request.mutation_timeout": "The operation response timed out. The interface has recovered; the result may already be applied. Refresh to confirm before submitting again.", "request.invalid_response": "The local service returned an unrecognised response ({status}). Restart FMODD and try again.", "request.retry_success": "Automatic refresh completed and the retry succeeded", "request.refresh_required": "Related data was refreshed automatically. Run the operation again.", "request.refresh_failed": "Data changed and automatic refresh failed: {error}", "request.service_unavailable": "Cannot connect to the local service. Check that FMODD is still running, then try again.", "request.failed": "Request failed", "request.operation_failed": "Operation failed: {detail}", "request.insufficient_balance": "Insufficient available balance", "request.stake_zero": "Stake must be greater than 0", "request.invalid_half_time_score": "Invalid half-time exact-score selection", "request.invalid_exact_score": "Invalid exact-score selection", "request.unknown_endpoint": "The requested feature endpoint does not exist", "request.unsupported_market": "Unsupported betting market: {market}",
      "dialog.purchase.product": "Confirm purchase of \u201c{name}\u201d", "dialog.purchase.amount": "Item amount", "dialog.purchase.method": "Payment method", "dialog.purchase.free": "Cheat mode: free purchase", "dialog.purchase.total": "Total", "dialog.purchase.confirm": "Confirm purchase", "dialog.acknowledge": "I understand",
      "home.global_usage": "Total usage", "home.active_days": "{count} active day(s)", "home.net_profit": "Total net profit", "home.max_profit": "Highest single-bet win", "home.longest_win": "Longest winning streak", "home.bet_count": "Total bets", "home.saves_used": "Saves used", "home.longest_loss": "Longest losing streak", "home.roi": "ROI {value}%", "home.net_profit_note": "Based on net profit", "home.current_streak_win": "Current win streak {count}", "home.current_streak_loss": "Current loss streak {count}", "home.bet_record": "Won {wins} \u00b7 Lost {losses} \u00b7 Void {pushes}", "home.betting_saves": "{count} saves with betting records", "home.max_loss": "Largest single-bet loss {amount}", "home.loading_global": "Summarising all saves", "career.scope_label": "Statistics scope", "career.scope_global": "Global", "career.scope_current": "Current save", "career.current_title": "Current save statistics", "career.loading_current": "Summarising current save", "home.global_error": "Could not read global statistics", "home.retry": "Retry", "home.load_failed": "Loading failed", "home.connected_refreshing": "Save connected; background data is still refreshing", "home.continue_reading": "Continuing to read the current save", "home.reading_current": "Reading the current save", "home.connection_pending": "The connection task has not finished. Please wait.",
      "home.bets": "{count} bet(s)",
      "refresh.fast": "Quick refresh", "refresh.fast_busy": "Quick refresh in progress", "refresh.full": "Full refresh", "refresh.full_busy": "Full refresh in progress", "refresh.results": "Settle results", "refresh.results_busy": "Settling results", "refresh.change_save": "Refresh after changing save", "refresh.apply": "Apply and refresh", "refresh.busy": "Refreshing",
      "manager.employment.both": "Club + national team", "manager.employment.club": "Club", "manager.employment.national": "National team", "manager.employment.unemployed": "Unemployed", "manager.fallback": "Manager {id}", "manager.current": "the current manager", "manager.id": "Manager ID {id}", "manager.follow_auto": "Use automatic detection", "manager.merge_accounts": "Merge same-ID accounts", "manager.merge_title": "Merge the current {count} same-ID account(s) into a new account", "manager.merge_unavailable": "At least two accounts with the same ID are required", "manager.unsupported_game": "No supported game version detected", "manager.switching_game": "Switching to {version}", "manager.club_change.title": "Managed club change detected", "manager.club_change.confirm": "Confirm switch", "manager.club_change.message": "{manager}\u2019s managed club changed from \u201c{previous}\u201d to \u201c{next}\u201d. Switch to the new club? FMODD will read its data and keep the current manager account.", "manager.club_change_confirmed": "Managed club change confirmed; reading the new club data", "manager.club_change_polling": "Switching managed club...", "manager.club_change_cancelled": "Managed club change cancelled", "manager.unknown_club": "Unknown club", "manager.club_fallback": "Club {id} ", "manager.unemployed.title": "Confirm manager status", "manager.unemployed.confirm": "Confirm unemployment and continue", "manager.unemployed.message": "Human manager \u201c{manager}\u201d was detected, but no managed team was found. Confirm that this manager is currently unemployed. ODD will remain available and will recognise a new club automatically.", "manager.unemployed_started": "Unemployment confirmed; reading available markets", "manager.unemployed_ready": "Unemployment confirmed; current market reading will continue", "manager.unemployed_polling": "Reading markets available to the unemployed manager...", "manager.refreshing": "A refresh is already in progress. Please wait.", "manager.selected_started": "Manager selected; connecting to the current save", "manager.selected_ready": "Manager account switched; current market reading will continue", "manager.selected_polling": "Connecting the selected manager...",
      "topbar.processing": "Processing \u00b7 {operation}", "topbar.game_running": "Game is running", "topbar.waiting_connection": "Waiting for connection", "topbar.cache_pending": "Cached markets need verification", "topbar.waiting_markets": "Waiting for markets", "topbar.up_to_date": "Up to date", "topbar.up_to_date_settled": "Up to date \u00b7 {count} bet(s) settled", "page.requires_save": "Open a Football Manager save and select Connect save first", "page.requires_game": "Start Football Manager, then connect a save",
      "shell.select.empty": "No options available", "shell.select.aria": "Choose an option", "shell.select.placeholder": "Select an option", "funding.daily_spend": "Daily spending",
      "home.startup_loading_detail": "Reading the current save, fixtures and teams", "home.connecting_service": "Connecting to the local service", "home.connecting_progress": "Connecting to save · {percent}%", "home.manager_id": "Manager ID {id}", "home.save_id": "Save {id}", "home.identifying_save": "Detecting save", "refresh.status_failed": "Could not read refresh status", "refresh.timeout": "Market refresh timed out. Check that the game is still running.",
      "shop.product_fallback": "product", "inventory.operation_done": "Operation completed", "inventory.operation_busy": "An item operation is already in progress. Please wait.", "operations.unconfirmed_detail": "FMODD closed before the final result was confirmed. Refresh the relevant page to check.", "operations.background_not_started": "The background task did not start. Check the current status and try again.", "operations.connection_success": "Save connected", "operations.connection_incomplete": "Save connection did not complete", "operations.refresh_completed": "Refresh completed",
      "operations.route.connect": "Connect save", "operations.route.merge_accounts": "Merge same-ID accounts", "operations.route.refresh_save": "Full save refresh", "operations.route.refresh_markets": "Refresh markets", "operations.route.refresh_club": "Refresh club data", "operations.route.scan_world_clubs": "Scan world clubs", "operations.route.refresh_group": "Refresh group data", "operations.route.transfer_club_funds": "Transfer club funds", "operations.route.buy_shop_items": "Buy shop items", "operations.route.buy_training_equipment": "Buy training equipment", "operations.route.unlock_training_floor": "Unlock training floor", "operations.route.manage_training_equipment": "Manage training equipment", "operations.route.arrange_training": "Arrange training", "operations.route.cancel_training": "Cancel training", "operations.route.unlock_activity_centre": "Unlock Activity Centre", "operations.route.buy_activity_facility": "Buy activity facility", "operations.route.learn_player_language": "Learn player language", "operations.route.run_player_activity": "Run player activity", "operations.route.adjust_treatment": "Adjust treatment plan", "operations.route.switch_canteen_plan": "Switch canteen plan", "operations.route.grant_sea_cucumber": "Grant sea-cucumber reward", "operations.route.manage_inventory": "Manage inventory items", "operations.route.run_group_operation": "Run group operation", "operations.route.run_fund_operation": "Manage funds", "operations.route.schedule_salary": "Schedule salary payment", "operations.route.adjust_league_points": "Adjust league points",
      "operations.location.connect": "Home · Save connection", "operations.location.save_account": "Settings · Save account", "operations.location.settings_markets": "Settings · Markets", "operations.location.markets_refresh": "Markets · Refresh", "operations.location.club_details": "Club · Club details", "operations.location.world_club_directory": "World Clubs · Club directory", "operations.location.group_details": "My Group · Group details", "operations.location.group_funds": "My Group · Club funds", "operations.location.shop_cart": "Shop · Cart", "operations.location.training_equipment": "Training Ground · Equipment", "operations.location.training_floor": "Training Ground · Floor unlock", "operations.location.training_tasks": "Training Ground · Training tasks", "operations.location.activity_floor": "Activity Centre · Floor construction", "operations.location.activity_facilities": "Activity Centre · Facility construction", "operations.location.activity_language": "Activity Centre · Language classroom", "operations.location.activity_players": "Activity Centre · Player activities", "operations.location.medical_treatment": "Medical Centre · Treatment plan", "operations.location.canteen_plan": "Canteen · Meal plan", "operations.location.canteen_rewards": "Canteen · Sea-cucumber rewards", "operations.location.inventory": "Inventory · Item management", "operations.location.group_operations": "My Group · Club operations", "operations.location.bank_operations": "Bank · Funds", "operations.location.salary": "Bank · Salary payments", "operations.location.league_points": "Inventory · League points",
    }),
    "zh-CN": Object.freeze({
      "shell.intelligence_title.one": "情报中心发现 {count} 场可获取情报的比赛", "shell.intelligence_title.other": "情报中心发现 {count} 场可获取情报的比赛", "shell.intelligence_aria.one": "活动，情报中心有 {count} 场可获取情报的比赛", "shell.intelligence_aria.other": "活动，情报中心有 {count} 场可获取情报的比赛", "home.active_days.one": "{count} 个活跃日", "home.active_days.other": "{count} 个活跃日", "home.bets.one": "{count} 笔", "home.bets.other": "{count} 笔", "manager.merge_title.one": "将当前同 ID 账户合并为新账户", "manager.merge_title.other": "将当前 {count} 个同 ID 账户合并为新账户", "topbar.up_to_date_settled.one": "已是最新 · 已结算 {count} 个注单", "topbar.up_to_date_settled.other": "已是最新 · 已结算 {count} 个注单",
      "common.cancel": "取消", "common.close": "关闭", "common.confirm": "确认", "common.ok": "确定",
      "funding.available": "可用资金", "funding.bank": "银行 {amount}", "funding.wallet": "钱包 {amount}", "funding.recurring": "{label} {amount}",
      "time.tbc": "时间待定", "shell.game_time": "游戏时间 {date} {time}", "shell.not_connected": "未连接存档", "shell.market_duration": "90分钟",
      "shell.wallet_balance": "钱包，余额 {amount}", "shell.intelligence_title": "情报中心发现 {count} 场可获取情报的比赛", "shell.intelligence_aria": "活动，情报中心有 {count} 场可获取情报的比赛", "shell.activities": "活动",
      "request.in_progress": "该操作正在处理中，请勿重复点击", "request.state_timeout": "存档资料仍在后台读取，界面会自动继续同步，请勿重复点击刷新", "request.read_timeout": "读取本地服务超时，界面已恢复；后台读取可能仍在继续，请稍后重试", "request.mutation_timeout": "操作响应超时，界面已恢复；结果可能已在后台生效，请先刷新确认，不要连续重复提交", "request.invalid_response": "本地服务返回了无法识别的响应（{status}），请重启工具后重试", "request.retry_success": "已自动刷新后重试成功", "request.refresh_required": "相关数据已自动刷新，请重新执行刚才的操作", "request.refresh_failed": "数据已变化，自动刷新失败：{error}", "request.service_unavailable": "无法连接本地服务，请确认 FMODD 仍在运行后重试", "request.failed": "请求失败", "request.operation_failed": "操作失败：{detail}", "request.insufficient_balance": "可用余额不足", "request.stake_zero": "下注金额必须大于 0", "request.invalid_half_time_score": "半场精确比分选项无效", "request.invalid_exact_score": "精确比分选项无效", "request.unknown_endpoint": "请求的功能接口不存在", "request.unsupported_market": "不支持的投注玩法：{market}",
      "dialog.purchase.product": "确认购买「{name}」", "dialog.purchase.amount": "商品金额", "dialog.purchase.method": "支付方式", "dialog.purchase.free": "作弊模式0元购", "dialog.purchase.total": "合计", "dialog.purchase.confirm": "确认购买", "dialog.acknowledge": "我知道了",
      "home.global_usage": "累计使用时间", "home.active_days": "{count} 个活跃日", "home.net_profit": "累计净收益", "home.max_profit": "最大单笔赢额", "home.longest_win": "最长连红", "home.bet_count": "总投注次数", "home.saves_used": "使用过的存档", "home.longest_loss": "最长连黑", "home.roi": "ROI {value}%", "home.net_profit_note": "按净盈利计算", "home.current_streak_win": "当前连红 {count}", "home.current_streak_loss": "当前连黑 {count}", "home.bet_record": "赢 {wins} · 输 {losses} · 退 {pushes}", "home.betting_saves": "{count} 个有投注记录", "home.max_loss": "最大单笔亏损 {amount}", "home.loading_global": "正在汇总全部存档", "career.scope_label": "统计范围", "career.scope_global": "全局", "career.scope_current": "本存档", "career.current_title": "本存档统计", "career.loading_current": "正在汇总本存档", "home.global_error": "无法读取全局统计", "home.retry": "重试", "home.load_failed": "读取失败", "home.connected_refreshing": "存档已连接，后台数据仍在刷新", "home.continue_reading": "正在继续读取当前存档", "home.reading_current": "正在读取当前存档", "home.connection_pending": "连接任务尚未结束，请稍候",
      "home.bets": "{count} 笔",
      "refresh.fast": "快速刷新", "refresh.fast_busy": "快速刷新中", "refresh.full": "全量刷新", "refresh.full_busy": "全量刷新中", "refresh.results": "结算赛果", "refresh.results_busy": "结算中", "refresh.change_save": "更换存档刷新", "refresh.apply": "应用并刷新", "refresh.busy": "刷新中",
      "manager.employment.both": "俱乐部＋国家队", "manager.employment.club": "俱乐部", "manager.employment.national": "国家队", "manager.employment.unemployed": "无业", "manager.fallback": "经理 {id}", "manager.current": "当前经理", "manager.id": "经理 ID {id}", "manager.follow_auto": "跟随自动识别", "manager.merge_accounts": "合并同ID账户", "manager.merge_title": "将当前 {count} 个同 ID 账户合并为新账户", "manager.merge_unavailable": "需要至少两个同 ID 账户", "manager.unsupported_game": "未识别到支持的游戏版本", "manager.switching_game": "正在切换到 {version}", "manager.club_change.title": "检测到执教俱乐部变化", "manager.club_change.confirm": "确认切换", "manager.club_change.message": "检测到{manager}的执教俱乐部已从“{previous}”变为“{next}”。是否切换到新俱乐部？确认后将读取新俱乐部资料，并沿用当前经理账户。", "manager.club_change_confirmed": "已确认更换执教俱乐部，正在读取新俱乐部资料", "manager.club_change_polling": "正在切换执教俱乐部...", "manager.club_change_cancelled": "已取消本次执教俱乐部切换", "manager.unknown_club": "未知俱乐部", "manager.club_fallback": "俱乐部 {id}", "manager.unemployed.title": "确认经理状态", "manager.unemployed.confirm": "确认无业并继续", "manager.unemployed.message": "已识别到人类经理“{manager}”，但暂时没有找到执教球队。请确认该经理目前确实处于无业状态；确认后可以使用 ODD，入职俱乐部后会自动识别并沿用当前账户。", "manager.unemployed_started": "已确认无业，正在读取盘口", "manager.unemployed_ready": "已确认无业，将继续当前盘口读取", "manager.unemployed_polling": "正在读取无业经理可用盘口...", "manager.refreshing": "当前正在刷新，请稍候", "manager.selected_started": "已选择经理，正在连接当前存档", "manager.selected_ready": "已切换经理账户，沿用当前盘口", "manager.selected_polling": "正在连接所选经理...",
      "topbar.processing": "正在处理 · {operation}", "topbar.game_running": "游戏已启动", "topbar.waiting_connection": "等待连接", "topbar.cache_pending": "缓存盘口待核对", "topbar.waiting_markets": "等待盘口", "topbar.up_to_date": "已是最新", "topbar.up_to_date_settled": "已是最新 · 已结算{count}个注单", "page.requires_save": "请先进入 Football Manager 存档并点击连接存档", "page.requires_game": "请先启动 Football Manager，再连接存档",
      "shell.select.empty": "没有可选项", "shell.select.aria": "选择选项", "shell.select.placeholder": "请选择", "funding.daily_spend": "每日支出",
      "home.startup_loading_detail": "正在读取当前存档、赛程和队伍资料", "home.connecting_service": "正在连接本地服务", "home.connecting_progress": "正在连接存档 · {percent}%", "home.manager_id": "经理 ID {id}", "home.save_id": "存档 {id}", "home.identifying_save": "正在识别存档", "refresh.status_failed": "无法读取刷新状态", "refresh.timeout": "盘口刷新超时，请确认游戏仍在运行",
      "shop.product_fallback": "商品", "inventory.operation_done": "处理完成", "inventory.operation_busy": "已有道具正在处理中，请稍候", "operations.unconfirmed_detail": "程序关闭前未确认最终结果，请刷新相关页面核对", "operations.background_not_started": "后台任务未启动，请查看当前状态后重试", "operations.connection_success": "已连接当前存档", "operations.connection_incomplete": "连接存档未完成", "operations.refresh_completed": "刷新完成",
      "operations.route.connect": "连接存档", "operations.route.merge_accounts": "合并同ID账户", "operations.route.refresh_save": "完整刷新存档", "operations.route.refresh_markets": "刷新盘口", "operations.route.refresh_club": "刷新球队资料", "operations.route.scan_world_clubs": "扫描世界俱乐部", "operations.route.refresh_group": "刷新集团资料", "operations.route.transfer_club_funds": "划转俱乐部资金", "operations.route.buy_shop_items": "购买商店物品", "operations.route.buy_training_equipment": "购买训练器材", "operations.route.unlock_training_floor": "解锁训练场楼层", "operations.route.manage_training_equipment": "调整训练器材", "operations.route.arrange_training": "安排训练", "operations.route.cancel_training": "取消训练", "operations.route.unlock_activity_centre": "解锁活动中心", "operations.route.buy_activity_facility": "购买活动设施", "operations.route.learn_player_language": "学习球员语言", "operations.route.run_player_activity": "执行球员活动", "operations.route.adjust_treatment": "调整治疗方案", "operations.route.switch_canteen_plan": "切换食堂方案", "operations.route.grant_sea_cucumber": "发放海参奖励", "operations.route.manage_inventory": "使用或管理物品", "operations.route.run_group_operation": "执行集团操作", "operations.route.run_fund_operation": "执行资金操作", "operations.route.schedule_salary": "设置工资发放", "operations.route.adjust_league_points": "调整联赛积分",
      "operations.location.connect": "首页 · 存档连接", "operations.location.save_account": "设置 · 存档账户", "operations.location.settings_markets": "设置 · 盘口", "operations.location.markets_refresh": "盘口 · 刷新", "operations.location.club_details": "球队 · 球队资料", "operations.location.world_club_directory": "世界俱乐部 · 俱乐部目录", "operations.location.group_details": "我的集团 · 集团资料", "operations.location.group_funds": "我的集团 · 俱乐部资金", "operations.location.shop_cart": "商店 · 购物车", "operations.location.training_equipment": "训练场 · 器材购买", "operations.location.training_floor": "训练场 · 楼层解锁", "operations.location.training_tasks": "训练场 · 训练任务", "operations.location.activity_floor": "活动中心 · 楼层建设", "operations.location.activity_facilities": "活动中心 · 设施建设", "operations.location.activity_language": "活动中心 · 语言教室", "operations.location.activity_players": "活动中心 · 球员活动", "operations.location.medical_treatment": "医疗中心 · 治疗方案", "operations.location.canteen_plan": "球员食堂 · 膳食方案", "operations.location.canteen_rewards": "球员食堂 · 海参奖励", "operations.location.inventory": "物品 · 道具管理", "operations.location.group_operations": "我的集团 · 俱乐部操作", "operations.location.bank_operations": "银行 · 资金操作", "operations.location.salary": "银行 · 工资发放", "operations.location.league_points": "物品 · 联赛积分",
    }),
    "ko-KR": Object.freeze({
      "shell.intelligence_title.one": "정보 센터에서 정보 획득이 가능한 경기 {count}건을 찾았습니다", "shell.intelligence_title.other": "정보 센터에서 정보 획득이 가능한 경기 {count}건을 찾았습니다", "shell.intelligence_aria.one": "활동, 정보 센터에 정보 획득이 가능한 경기 {count}건이 있습니다", "shell.intelligence_aria.other": "활동, 정보 센터에 정보 획득이 가능한 경기 {count}건이 있습니다", "home.active_days.one": "활성 일수 {count}일", "home.active_days.other": "활성 일수 {count}일", "home.bets.one": "{count}회", "home.bets.other": "{count}회", "manager.merge_title.one": "현재 동일 ID 계정을 새 계정으로 병합", "manager.merge_title.other": "현재 동일 ID 계정 {count}개를 새 계정으로 병합", "topbar.up_to_date_settled.one": "최신 상태 · 베팅 {count}건 정산됨", "topbar.up_to_date_settled.other": "최신 상태 · 베팅 {count}건 정산됨",
      "common.cancel": "취소", "common.close": "닫기", "common.confirm": "확인", "common.ok": "확인",
      "funding.available": "사용 가능한 자금", "funding.bank": "은행 {amount}", "funding.wallet": "지갑 {amount}", "funding.recurring": "{label} {amount}",
      "time.tbc": "시간 미정", "shell.game_time": "게임 시간 {date} {time}", "shell.not_connected": "연결된 저장 파일 없음", "shell.market_duration": "90분",
      "shell.wallet_balance": "지갑, 잔액 {amount}", "shell.intelligence_title": "정보 센터에서 정보 획득이 가능한 경기 {count}건을 찾았습니다", "shell.intelligence_aria": "활동, 정보 센터에 정보 획득이 가능한 경기 {count}건이 있습니다", "shell.activities": "활동",
      "request.in_progress": "이 작업은 이미 진행 중입니다. 다시 제출하지 마세요.", "request.state_timeout": "저장 데이터를 백그라운드에서 계속 읽고 있습니다. 화면이 자동으로 동기화되니 새로 고침을 반복하지 마세요.", "request.read_timeout": "로컬 서비스 읽기 시간이 초과되었습니다. 화면은 복구되었으며 백그라운드 읽기가 계속될 수 있으니 잠시 후 다시 시도하세요.", "request.mutation_timeout": "작업 응답 시간이 초과되었습니다. 화면은 복구되었고 결과가 이미 적용되었을 수 있습니다. 다시 제출하기 전에 새로 고침으로 확인하세요.", "request.invalid_response": "로컬 서비스가 인식할 수 없는 응답({status})을 반환했습니다. FMODD를 다시 시작한 뒤 시도하세요.", "request.retry_success": "자동 새로 고침 후 재시도에 성공했습니다", "request.refresh_required": "관련 데이터를 자동으로 새로 고쳤습니다. 방금 작업을 다시 실행하세요.", "request.refresh_failed": "데이터가 변경되어 자동 새로 고침에 실패했습니다: {error}", "request.service_unavailable": "로컬 서비스에 연결할 수 없습니다. FMODD가 실행 중인지 확인한 뒤 다시 시도하세요.", "request.failed": "요청에 실패했습니다", "request.operation_failed": "작업 실패: {detail}", "request.insufficient_balance": "사용 가능한 잔액이 부족합니다", "request.stake_zero": "베팅 금액은 0보다 커야 합니다", "request.invalid_half_time_score": "잘못된 전반 정확 스코어 선택입니다", "request.invalid_exact_score": "잘못된 정확 스코어 선택입니다", "request.unknown_endpoint": "요청한 기능 엔드포인트가 없습니다", "request.unsupported_market": "지원하지 않는 베팅 시장: {market}",
      "dialog.purchase.product": "\u201c{name}\u201d 구매를 확인하세요", "dialog.purchase.amount": "상품 금액", "dialog.purchase.method": "결제 방식", "dialog.purchase.free": "치트 모드: 무료 구매", "dialog.purchase.total": "합계", "dialog.purchase.confirm": "구매 확인", "dialog.acknowledge": "알겠습니다",
      "home.global_usage": "총 사용 시간", "home.active_days": "활성 일수 {count}일", "home.net_profit": "누적 순수익", "home.max_profit": "최고 단일 베팅 수익", "home.longest_win": "최장 연승", "home.bet_count": "총 베팅 횟수", "home.saves_used": "사용한 저장 파일", "home.longest_loss": "최장 연패", "home.roi": "ROI {value}%", "home.net_profit_note": "순이익 기준", "home.current_streak_win": "현재 {count}연승", "home.current_streak_loss": "현재 {count}연패", "home.bet_record": "승 {wins} · 패 {losses} · 적중취소 {pushes}", "home.betting_saves": "베팅 기록 {count}개", "home.max_loss": "최대 단일 베팅 손실 {amount}", "home.loading_global": "모든 저장 파일을 집계하는 중", "career.scope_label": "통계 범위", "career.scope_global": "전체", "career.scope_current": "현재 저장 파일", "career.current_title": "현재 저장 파일 통계", "career.loading_current": "현재 저장 파일을 집계하는 중", "home.global_error": "전체 통계를 읽을 수 없습니다", "home.retry": "다시 시도", "home.load_failed": "읽기 실패", "home.connected_refreshing": "저장 파일이 연결되었으며 백그라운드 데이터를 새로 고치는 중입니다", "home.continue_reading": "현재 저장 파일을 계속 읽는 중", "home.reading_current": "현재 저장 파일을 읽는 중", "home.connection_pending": "연결 작업이 아직 끝나지 않았습니다. 기다려 주세요.",
      "home.bets": "{count}회",
      "refresh.fast": "빠른 새로 고침", "refresh.fast_busy": "빠른 새로 고침 중", "refresh.full": "전체 새로 고침", "refresh.full_busy": "전체 새로 고침 중", "refresh.results": "결과 정산", "refresh.results_busy": "결과 정산 중", "refresh.change_save": "저장 파일 변경 후 새로 고침", "refresh.apply": "적용 및 새로 고침", "refresh.busy": "새로 고침 중",
      "manager.employment.both": "클럽 + 국가대표", "manager.employment.club": "클럽", "manager.employment.national": "국가대표", "manager.employment.unemployed": "무직", "manager.fallback": "감독 {id}", "manager.current": "현재 감독", "manager.id": "감독 ID {id}", "manager.follow_auto": "자동 감지 사용", "manager.merge_accounts": "동일 ID 계정 병합", "manager.merge_title": "현재 동일 ID 계정 {count}개를 새 계정으로 병합", "manager.merge_unavailable": "동일 ID 계정이 두 개 이상 필요합니다", "manager.unsupported_game": "지원되는 게임 버전을 찾지 못했습니다", "manager.switching_game": "{version}(으)로 전환하는 중", "manager.club_change.title": "담당 클럽 변경 감지", "manager.club_change.confirm": "전환 확인", "manager.club_change.message": "{manager}의 담당 클럽 변경: \u201c{previous}\u201d → \u201c{next}\u201d. 새 클럽으로 전환할까요? FMODD가 데이터를 읽고 현재 감독 계정을 유지합니다.", "manager.club_change_confirmed": "담당 클럽 변경을 확인했습니다. 새 클럽 데이터를 읽는 중", "manager.club_change_polling": "담당 클럽을 전환하는 중...", "manager.club_change_cancelled": "담당 클럽 전환을 취소했습니다", "manager.unknown_club": "알 수 없는 클럽", "manager.club_fallback": "클럽 {id}", "manager.unemployed.title": "감독 상태 확인", "manager.unemployed.confirm": "무직 확인 후 계속", "manager.unemployed.message": "인간 감독 \u201c{manager}\u201d을(를) 찾았지만 담당 팀을 찾지 못했습니다. 현재 무직 상태인지 확인하세요. ODD는 계속 사용할 수 있고 새 클럽에 취임하면 자동으로 인식합니다.", "manager.unemployed_started": "무직을 확인했습니다. 이용 가능한 시장을 읽는 중", "manager.unemployed_ready": "무직을 확인했습니다. 현재 시장 조회를 계속합니다", "manager.unemployed_polling": "무직 감독에게 이용 가능한 시장을 읽는 중...", "manager.refreshing": "새로 고침이 진행 중입니다. 기다려 주세요.", "manager.selected_started": "감독을 선택했습니다. 현재 저장 파일에 연결하는 중", "manager.selected_ready": "감독 계정을 전환했습니다. 현재 시장 조회를 계속합니다", "manager.selected_polling": "선택한 감독을 연결하는 중...",
      "topbar.processing": "처리 중 · {operation}", "topbar.game_running": "게임 실행 중", "topbar.waiting_connection": "연결 대기 중", "topbar.cache_pending": "캐시된 시장 확인 대기", "topbar.waiting_markets": "시장 대기 중", "topbar.up_to_date": "최신 상태", "topbar.up_to_date_settled": "최신 상태 · 베팅 {count}건 정산됨", "page.requires_save": "Football Manager 저장 파일을 연 뒤 먼저 저장 파일 연결을 선택하세요", "page.requires_game": "Football Manager를 시작한 뒤 저장 파일을 연결하세요",
      "shell.select.empty": "선택 가능한 항목이 없습니다", "shell.select.aria": "옵션 선택", "shell.select.placeholder": "옵션을 선택하세요", "funding.daily_spend": "일일 지출",
      "home.startup_loading_detail": "현재 저장 파일, 일정 및 팀을 읽는 중", "home.connecting_service": "로컬 서비스에 연결하는 중", "home.connecting_progress": "저장 파일 연결 중 · {percent}%", "home.manager_id": "감독 ID {id}", "home.save_id": "저장 파일 {id}", "home.identifying_save": "저장 파일을 확인하는 중", "refresh.status_failed": "새로 고침 상태를 읽을 수 없습니다", "refresh.timeout": "시장 새로 고침 시간이 초과되었습니다. 게임이 계속 실행 중인지 확인하세요.",
      "shop.product_fallback": "상품", "inventory.operation_done": "작업 완료", "inventory.operation_busy": "아이템 작업이 이미 진행 중입니다. 기다려 주세요.", "operations.unconfirmed_detail": "FMODD가 종료되기 전에 최종 결과를 확인하지 못했습니다. 관련 페이지를 새로 고쳐 확인하세요.", "operations.background_not_started": "백그라운드 작업이 시작되지 않았습니다. 현재 상태를 확인한 뒤 다시 시도하세요.", "operations.connection_success": "저장 파일에 연결됨", "operations.connection_incomplete": "저장 파일 연결이 완료되지 않았습니다", "operations.refresh_completed": "새로 고침 완료",
      "operations.route.connect": "저장 파일 연결", "operations.route.merge_accounts": "동일 ID 계정 병합", "operations.route.refresh_save": "저장 파일 전체 새로 고침", "operations.route.refresh_markets": "시장 새로 고침", "operations.route.refresh_club": "클럽 데이터 새로 고침", "operations.route.scan_world_clubs": "세계 클럽 스캔", "operations.route.refresh_group": "그룹 데이터 새로 고침", "operations.route.transfer_club_funds": "클럽 자금 이체", "operations.route.buy_shop_items": "상점 아이템 구매", "operations.route.buy_training_equipment": "훈련 장비 구매", "operations.route.unlock_training_floor": "훈련장 층 해제", "operations.route.manage_training_equipment": "훈련 장비 관리", "operations.route.arrange_training": "훈련 배정", "operations.route.cancel_training": "훈련 취소", "operations.route.unlock_activity_centre": "활동 센터 해제", "operations.route.buy_activity_facility": "활동 시설 구매", "operations.route.learn_player_language": "선수 언어 학습", "operations.route.run_player_activity": "선수 활동 실행", "operations.route.adjust_treatment": "치료 계획 조정", "operations.route.switch_canteen_plan": "식당 계획 전환", "operations.route.grant_sea_cucumber": "해삼 보상 지급", "operations.route.manage_inventory": "아이템 관리", "operations.route.run_group_operation": "그룹 작업 실행", "operations.route.run_fund_operation": "자금 관리", "operations.route.schedule_salary": "급여 지급 예약", "operations.route.adjust_league_points": "리그 승점 조정",
      "operations.location.connect": "홈 · 저장 파일 연결", "operations.location.save_account": "설정 · 저장 계정", "operations.location.settings_markets": "설정 · 시장", "operations.location.markets_refresh": "시장 · 새로 고침", "operations.location.club_details": "클럽 · 클럽 상세", "operations.location.world_club_directory": "세계 클럽 · 클럽 목록", "operations.location.group_details": "내 그룹 · 그룹 정보", "operations.location.group_funds": "내 그룹 · 클럽 자금", "operations.location.shop_cart": "상점 · 장바구니", "operations.location.training_equipment": "훈련장 · 장비", "operations.location.training_floor": "훈련장 · 층 해제", "operations.location.training_tasks": "훈련장 · 훈련 작업", "operations.location.activity_floor": "활동 센터 · 층 건설", "operations.location.activity_facilities": "활동 센터 · 시설 건설", "operations.location.activity_language": "활동 센터 · 언어 교실", "operations.location.activity_players": "활동 센터 · 선수 활동", "operations.location.medical_treatment": "의료 센터 · 치료 계획", "operations.location.canteen_plan": "식당 · 식사 계획", "operations.location.canteen_rewards": "식당 · 해삼 보상", "operations.location.inventory": "아이템 · 아이템 관리", "operations.location.group_operations": "내 그룹 · 클럽 작업", "operations.location.bank_operations": "은행 · 자금 관리", "operations.location.salary": "은행 · 급여 지급", "operations.location.league_points": "아이템 · 리그 승점",
    }),
  });

  const legacy = Object.freeze({
    "en-GB": Object.freeze({"取消":"Cancel", "确定":"OK", "关闭":"Close", "未连接存档":"No save connected", "90分钟":"90 min"}),
    "zh-CN": Object.freeze({}),
    "ko-KR": Object.freeze({"取消":"취소", "确定":"확인", "关闭":"닫기", "未连接存档":"연결된 저장 파일 없음", "90分钟":"90분"}),
  });

  window.FMODDI18nModules = Array.isArray(window.FMODDI18nModules) ? window.FMODDI18nModules : [];
  window.FMODDI18nModules.push(Object.freeze({messages, legacy}));
})();
